esphome:
  name: xiaoc3-blind-roller-test
  friendly_name: xiaoc3-blind-roller-test

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret blinds_api_key

ota:
  - platform: esphome
    password: !secret blinds_ota_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xiaoc3-Blind-Roller-Test"
    password: !secret blinds_fallback_password

captive_portal:
    

sensor:
  - platform: adc
    id: slide_pos
    pin: GPIO03
    name: "Slide Potentiometer Value"
    attenuation: auto
    update_interval: 500ms

  - platform: adc
    id: hall_sens
    pin: GPIO04
    name: "Hall Effect Sensor Value"
    attenuation: auto
    update_interval: 500ms


fan:
  - platform: hbridge
    id: motor_1
    name: "Blind Motor"
    pin_a: mot_fwd_speed
    pin_b: mot_dir_switch
    decay_mode: slow   # slow decay mode (coasting) or fast decay (braking).
    speed_count: 20

output:
  - platform: ledc
    id: mot_fwd_speed
    pin: GPIO21
  - platform: ledc
    id: mot_dir_switch
    pin: GPIO7